src/main/java/model/Client.java
package model;

import javax.persistence.*;

/**
 * Model der Proyect
 */
@Entity
@Table(name = "Client", uniqueConstraints = {
        @UniqueConstraint(columnNames = "ID")})
public class Client {
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    private int id;

    @Column(name = "name")
    private String name;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

src/main/java/model/JPAutil.java
package model;

import javax.ejb.Stateless;
import javax.enterprise.inject.Produces;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.PersistenceContext;


/**
 * Hier ist erzeugt die entitty manager,
 * um in die Dao zu nutzen
 */
@Stateless
public class JPAutil{
    private static final String PUName = "jpa";
    private static EntityManagerFactory factory;

    @PersistenceContext(unitName = "jpa", name = "jpa")
    private EntityManager em;

    @Produces
    public EntityManager getEntityManager(){
        return em;
    }
    ////JUST TO PRUBEEEEE ////////
    private static  EntityManager entity;
    public static  EntityManager getEntityManegerP() {
        if (factory == null) {
            factory = Persistence.createEntityManagerFactory(PUName);
            entity = factory.createEntityManager();
        }
        return entity;
    }
    //////////////------///////////////////
    public static EntityManagerFactory getEntityManegerFactory() {
        if (factory == null) {
            factory = Persistence.createEntityManagerFactory(PUName);
        }
        return factory;
    }
    public static void shutDown() {
        if (factory != null) {
            factory.close();
        }
    }
}
  /**/

src/main/java/controller/ClientBean.java
package controller;

import dao.ClientDAO;
import model.Client;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;
//Resive peticiones desde el navegador

/**
 * Diese Klass ist Bean Erzegen,
 * die mit JPA kommunizieren soll
 */
@Named
@RequestScoped
public class ClientBean implements Serializable {

    String username, id;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public List<Client> AllClients() {
        ClientDAO clientDAO = new ClientDAO();
        return clientDAO.findall();
    }

    public String edit(String id) {
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("id", id);
        return "edit?faces-redirect=true";
    }

    public void erase(String id) {
        ClientDAO clientDAO = new ClientDAO();
        clientDAO.remove(Integer.parseInt(id));
    }

    public String newClient() {
        return "join?faces-redirect=true";
    }


}

src/main/java/controller/EditBean.java
package controller;

import dao.ClientDAO;
import model.Client;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;

@RequestScoped
@Named
public class EditBean implements Serializable {

    String name, id;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserID() {
        return (String) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("id");
    }

    public Client getUser() {
        ClientDAO clientDAO = new ClientDAO();
        return clientDAO.findbyId(Integer.parseInt(getUserID()));
    }

    public String clientEdit() {
        ClientDAO clientDAO = new ClientDAO();
        Client client1 = clientDAO.findbyId(Integer.parseInt(getUserID()));
        client1.setName(name);
        clientDAO.update(client1);
        return "index?Faces-redirect=true";
    }
}

src/main/java/controller/JoinBean.java
package controller;

import dao.ClientDAO;
import model.Client;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class JoinBean {
    String id, name;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String newOne() {
        Client client = new Client();
        client.setName(name);
        client.setId(Integer.parseInt(id));
        ClientDAO clientDAO = new ClientDAO();
        clientDAO.create(client);
        return "index?Faces-redirect=true";
    }
}

web/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>hola</title>
</h:head>
<h:body>

    <!-- <h:inputText value="#{editBean.userID}"/>
     <h:inputText value="#{editBean.user.name}"/>-->

    <h:dataTable value="#{editBean.getUser()}" var="clientName" border="5">
        <h:column>
            <f:facet name="header">ID</f:facet>
            <h:outputText value="#{clientName.id}"/>
        </h:column>
        <h:column>
            <f:facet name="header">Name</f:facet>
            <h:outputText value="#{clientName.name}"/>
        </h:column>
        <h:column>
            <h:form>
                <h:inputText placeholder="Username" value="#{editBean.name}" required="true"/>
                <h:commandButton action="#{editBean.clientEdit()}" value="editarNombre"></h:commandButton>
            </h:form>

        </h:column>

    </h:dataTable>
</h:body>
</html>

web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>hola</title>
</h:head>
<h:body>

    <h:dataTable value="#{clientBean.AllClients()}" var="clients" border="5">
        <h:column>
            <f:facet name="header">NAME</f:facet>
            <h:outputText value="#{clients.getName()}"/>
        </h:column>
        <h:column>
            <f:facet name="header">ID</f:facet>
            <h:outputText value="#{clients.id}"/>
        </h:column>
        <h:column>
            <f:facet name="header">Edit</f:facet>
            <h:form>
                <h:commandButton action="#{clientBean.edit(clients.id)}" value="editar"/>
            </h:form>
        </h:column>
        <h:column>
            <f:facet name="header">Remove</f:facet>
            <h:form>
                <h:commandButton action="#{clientBean.erase(clients.id)}" value="borrar"/>
            </h:form>
        </h:column>
    </h:dataTable>
    <h:form>

        <h:commandButton action="#{clientBean.newClient}" value="Crear"/>
    </h:form>
</h:body>
</html>

web/join.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>newClient</title>
</h:head>
<h:body>
    <h:form>
        <h:inputText placeholder="Username" value="#{joinBean.name}" required="true"/>
        <h:inputText placeholder="UserId" value="#{joinBean.id}" required="true"/>
        <h:commandButton action="#{joinBean.newOne()}" value="Crear"></h:commandButton>
    </h:form>
</h:body>
</html>